default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: mi_locations_development

test:
  <<: *default
  database: mi_locations_test

staging:
  <<: *default
  database: mi_locations_staging
  username: <%= Rails.application.credentials.STAGING_DB_USERNAME %>
  password: <%= Rails.application.credentials.STAGING_DB_PASSWORD %>

production:
  <<: *default
  database: mi_locations_production
  username: <%= Rails.application.credentials.PRODUCTION_DB_USERNAME %>
  password: <%= Rails.application.credentials.PRODUCTION_DB_PASSWORD %>
